#!/usr/bin/env python3
"""
Generate README.md from SHACL shapes and examples.
"""

import json
from pathlib import Path
from datetime import date

# Paths
SCRIPT_DIR = Path(__file__).parent.resolve()
PROJECT_ROOT = SCRIPT_DIR.parent
SHAPES_DIR = PROJECT_ROOT / "shapes"
EXAMPLES_DIR = PROJECT_ROOT / "examples"
STATS_FILE = SHAPES_DIR / "shapes_statistics.json"
OUTPUT_README = PROJECT_ROOT / "README.md"

# Base URL for documentation
DOC_BASE = "https://mobilitydcat-ap.github.io/mobilityDCAT-AP/releases/index.html"

# Map shape names to documentation anchors
SHAPE_DOCS = {
    "Address Agent": "properties-for-address-agent",
    "Agent": "properties-for-agent",
    "Assessment": "properties-for-assessment",
    "Catalog Record": "properties-for-catalogue-record",
    "Catalogue": "properties-for-catalogue",
    "Category Scheme": "properties-for-category-scheme",
    "Category": "properties-for-category",
    "Checksum": "properties-for-checksum",
    "Data Service": "properties-for-data-service",
    "Dataset": "properties-for-dataset",
    "Distribution": "properties-for-distribution",
    "Document": "properties-for-document",
    "Identifier": "properties-for-identifier",
    "Kind": "properties-for-kind",
    "License Document": "properties-for-licence-document",
    "Location": "properties-for-location",
    "Mobility Data Standard": "properties-for-mobility-data-standard",
    "Period Of Time": "properties-for-period-of-time",
    "Quality Annotation": "properties-for-quality-annotation",
    "Rights Statement": "properties-for-rights-statement",
}

README_TEMPLATE = """# mobilityDCAT-AP SHACL Validation

> Automated validation for mobilityDCAT-AP metadata using SHACL shapes

**Last Updated:** {date}

## Quick Stats

| Metric | Count |
|--------|-------|
| **Shapes** | {total_shapes} |
| **Total Properties** | {total_properties} |
| **Mandatory Properties** | {mandatory_properties} |

## Quick Start

### Combine Shapes
```bash
python scripts/combine_shapes.py
```

### Validate with Docker
```bash
# Build
docker build -f .docker/Dockerfile -t mobilitydcat-validator .

# Validate
docker run mobilitydcat-validator "https://example.com/catalog.ttl"
```

## Directory Structure
```
validationFiles/
├── shapes/                           # Individual SHACL shapes
├── scripts/                          # Automation tools
│   ├── combine_shapes.py            # Merge shapes
│   └── generate_readme.py           # Generate docs
├── .docker/                          # Docker validation
└── mobilitydcat-ap_shacl_shapes.ttl # Combined output
```

## Available Shapes

{shapes_table}

## Development Setup
```bash
# Create environment
uv venv
.venv\\Scripts\\Activate.ps1  # Windows

# Install dependencies
uv pip install -r requirements.txt

# Combine shapes + generate docs
python scripts/combine_shapes.py
python scripts/generate_readme.py
```

## 📚 Documentation

- [mobilityDCAT-AP Specification](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/)
- [SHACL W3C Spec](https://www.w3.org/TR/shacl/)
- [Docker Validation Guide](.docker/README.md)

*Auto-generated by `generate_readme.py` - do not edit manually*
"""


def load_statistics():
    """Load statistics from JSON file."""
    if not STATS_FILE.exists():
        return None
    
    with open(STATS_FILE, 'r', encoding='utf-8') as f:
        return json.load(f)


def generate_shapes_table(stats):
    """Generate clean markdown table with links."""
    if not stats:
        return "*Run `python scripts/combine_shapes.py` first.*"
    
    table = "| Shape | Documentation | File | Properties | Mandatory |\n"
    table += "|-------|---------------|------|------------|----------|\n"
    
    for shape in sorted(stats['shapes'], key=lambda x: x['shape_name']):
        name = shape['shape_name']
        file = shape['file_name']
        props = shape['total_properties']
        mandatory = shape['mandatory_properties']
        
        # Create documentation link
        doc_anchor = SHAPE_DOCS.get(name)
        if doc_anchor:
            doc_link = f"[📖 Spec]({DOC_BASE}#{doc_anchor})"
        else:
            doc_link = "—"
        
        table += f"| **{name}** | {doc_link} | [`{file}`](shapes/{file}) | {props} | {mandatory} |\n"
    
    return table


def generate_readme():
    """Generate the README file."""
    
    print("Generating README...")
    
    # Load statistics
    stats = load_statistics()
    
    if not stats:
        print("⚠️  No statistics found. Run combine_shapes.py first.")
        return False
    
    # Calculate totals
    total_shapes = len(stats['shapes'])
    total_properties = sum(s['total_properties'] for s in stats['shapes'])
    mandatory_properties = sum(s['mandatory_properties'] for s in stats['shapes'])
    
    # Generate table
    shapes_table = generate_shapes_table(stats)
    
    # Fill template
    readme_content = README_TEMPLATE.format(
        date=date.today().isoformat(),
        total_shapes=total_shapes,
        total_properties=total_properties,
        mandatory_properties=mandatory_properties,
        shapes_table=shapes_table
    )
    
    # Write README
    with open(OUTPUT_README, 'w', encoding='utf-8') as f:
        f.write(readme_content)
    
    print(f"✓ README generated: {OUTPUT_README}")
    print(f"  • {total_shapes} shapes")
    print(f"  • {total_properties} properties")
    print(f"  • {mandatory_properties} mandatory")
    
    return True


if __name__ == "__main__":
    success = generate_readme()
    exit(0 if success else 1)